# Generated by Django 4.0.5 on 2022-06-20 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='father_name',
            new_name='Father_Name',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='fname',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='lname',
            new_name='Last_Name',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='mother_name',
            new_name='Mother_Name',
        ),
    ]
