# Generated by Django 4.0.5 on 2022-06-20 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_info_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='date',
            new_name='Date_Of_Birth',
        ),
    ]
