# Generated by Django 4.0.5 on 2022-06-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_rename_date_info_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='branch',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
