# Generated by Django 4.0.5 on 2022-06-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_info_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='year',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
