# Generated by Django 4.0.5 on 2022-06-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_info_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
