# Generated by Django 4.0.5 on 2022-06-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_info_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='Contact_Number',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='Father_Contact_Number',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='Mother_Contact_Number',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
