# Generated by Django 4.0.5 on 2022-06-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_info_aadhar_number_alter_info_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='Address',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
