# Generated by Django 4.0.5 on 2022-06-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0010_info_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='Aadhar_Number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='Address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='Contact_Number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='Father_Contact_Number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='Mother_Contact_Number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
